# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
ansi_term-0.11.0
anyhow-1.0.34
atty-0.2.14
autocfg-1.0.1
bitflags-1.2.1
cargo-toml2-1.3.2
cfg-if-0.1.10
cfg-if-1.0.0
clap-2.33.3
const_fn-0.4.3
crossbeam-channel-0.5.0
crossbeam-deque-0.8.0
crossbeam-epoch-0.9.0
crossbeam-utils-0.8.0
either-1.6.1
fs_extra-1.2.0
getrandom-0.1.15
heck-0.3.1
hermit-abi-0.1.17
lazy_static-1.4.0
libc-0.2.80
log-0.4.11
memoffset-0.5.6
num_cpus-1.13.0
ppv-lite86-0.2.10
proc-macro-error-1.0.4
proc-macro-error-attr-1.0.4
proc-macro2-1.0.24
quote-1.0.7
rand-0.7.3
rand_chacha-0.2.2
rand_core-0.5.1
rand_hc-0.2.0
rayon-1.5.0
rayon-core-1.9.0
redox_syscall-0.1.57
remove_dir_all-0.5.3
remove_dir_all-0.6.1
scopeguard-1.1.0
serde-1.0.117
serde_derive-1.0.117
strsim-0.8.0
structopt-0.3.20
structopt-derive-0.4.13
syn-1.0.51
tempfile-3.1.0
textwrap-0.11.0
toml-0.5.7
unicode-segmentation-1.7.1
unicode-width-0.1.8
unicode-xid-0.2.1
vec_map-0.8.2
version_check-0.9.2
wasi-0.9.0+wasi-snapshot-preview1
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Simply and Easily cross-compile the Rust sysroot crates."
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/DianaNites/cargo-sysroot"
SRC_URI="
   https://github.com/DianaNites/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
   $(cargo_crate_uris ${CRATES})
"

RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0 WITH LLVM-exception MIT"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""

src_unpack() {
  cargo_src_unpack
}

src_configure() {
  cargo_gen_config
}

src_compile() {
  cargo_src_compile
}
