export IDEA_JDK=${IDEA_JDK=/usr/lib/jvm/jetbrains-jre-bin}
export CLION_JDK=${IDEA_JDK=/usr/lib/jvm/jetbrains-jre-bin}
export PYCHARM_JDK=${PYCHARM_JDK=/usr/lib/jvm/jetbrains-jre-bin}
export RIDER_JDK=${IDEA_JDK=/usr/lib/jvm/jetbrains-jre-bin}
export DATASPELL_JDK=${IDEA_JDK=/usr/lib/jvm/jetbrains-jre-bin}
export DATAGRIP_JDK=${IDEA_JDK=/usr/lib/jvm/jetbrains-jre-bin}
export GOLAND_JDK=${IDEA_JDK=/usr/lib/jvm/jetbrains-jre-bin}
export PHPSTORM_JDK=${IDEA_JDK=/usr/lib/jvm/jetbrains-jre-bin}
export RUBYMINE_JDK=${IDEA_JDK=/usr/lib/jvm/jetbrains-jre-bin}