JDK=/usr/lib/jvm/jetbrains-jre-bin
export IDEA_JDK=${IDEA_JDK=${JDK}}
export CLION_JDK=${IDEA_JDK=${JDK}}
export PYCHARM_JDK=${PYCHARM_JDK=${JDK}}
export RIDER_JDK=${RIDER_JDK=${JDK}}
export DATASPELL_JDK=${DATASPELL_JDK=${JDK}}
export DATAGRIP_JDK=${DATAGRIP_JDK=${JDK}}
export GOLAND_JDK=${GOLAND_JDK=${JDK}}
export PHPSTORM_JDK=${PHPSTORM_JDK=${JDK}}
export RUBYMINE_JDK=${RUBYMINE_JDK=${JDK}}
